resources:
  - name:       teams
    type:       OutgoingWebhook
    configuration:
      webhookName: teams
      path: /json

pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: my_send_hook_json
        type: Bash
        configuration:
          outputResources:
            - name: teams
        execution:
          onExecute:
            - jsonPayload="{\"runNumber\":\"$run_number\", \"stepName\":\"$step_name\"}"
            - set_payload teams "$jsonPayload"
          onFailure:
            - export res_teams_skipWebHook=true
          onSuccess:
            - echo "Payload sent by "$res_teams_name":"
            - echo $res_teams_payload

