resources:
  - name: simplehelmRepo_docker
     type: GitRepo
     configuration:
       gitProvider: github
       path: pipelines-example/simplehelm
       files:
         include: "Dockerfile|server.js|package.json"

   - name: simplehelmDockerImage
     type: Image
     configuration:
       registry: art-docker-local
       imageName: myproject/simplehelm
       imageTag: latest

pipelines:
  - name: build_image
    type: DockerBuild
    configuration:
      affinityGroup: buildAndPush
      integrations:
        - name: art-docker-local
      inputResources:
        - name: simplehelmRepo_docker
      dockerFileLocation: .
      dockerFileName: Dockerfile
      dockerImageName: myproject/simplehelm
      dockerImageTag: $run_number

  - name: push_image
    type: DockerPush
    configuration:
      affinityGroup: buildAndPush
      integrations:
        - name: art-docker-local
      targetRepository: myproject/simplehelm
      inputSteps:
        - name: build_image
      outputResources:
        - name: simplehelmDockerImage
